### ISSUE TITLE
Terrible typos, plz fix

### ISSUE THREAD

**Issue by VukoDrakkeinen** [Azahe/ing-scrapper#2]
Dude, c'mon.
`s/`[scrapper](https://en.wikipedia.org/wiki/Scrapper)`/`[scraper](https://en.wikipedia.org/wiki/Web_scraping)`/`
`s/retriver/retriever/`
`s/would browser/would a browser/` (and other missing articles)

**Comment by Azahe** [comment]
Hopefully resolved
